GET http://localhost:8000/api/roles
Accept: application/json

###
GET http://localhost:8000/api/roles/1
Accept: application/json

###
PUT http://localhost:8000/api/roles/1
Content-Type: application/json

{
  "role_id": 1,
  "name": "Admin"
}


###
DELETE http://localhost:8000/api/roles/2
Accept: application/json




###
POST http://localhost:8000/api/roles
Content-Type: application/json

{
  "role_id": 1,
  "name": "Admin"
}



